import { createContext, useContext, useState, useCallback, useMemo } from 'react';

const translations = {
    es: {
        // Navbar
        appSubtitle: 'Comparte y descubre tips sustentables',
        notifications: 'Notificaciones',
        noNotifications: 'Sin notificaciones',
        markAllRead: 'Marcar todo leído',
        myProfile: 'Mi Perfil',
        moderation: 'Moderación',
        logout: 'Cerrar sesión',
        login: 'Iniciar sesión',
        register: 'Registrarse',
        roleModerator: 'Moderador',
        roleUser: 'Usuario',
        // Home
        publishTip: 'Publicar Tip',
        mostRecent: 'Más recientes',
        mostPopular: 'Más populares',
        oldest: 'Más antiguos',
        noTipsCategory: 'No hay tips en esta categoría. ¡Sé el primero en aportar!',
        loadMore: 'Cargar más tips',
        endOfList: 'Has llegado al final',
        // Categories
        all: 'Todos',
        waste: 'Residuos',
        recycling: 'Reciclaje',
        energy: 'Energía',
        nature: 'Naturaleza',
        // TipCard
        like: 'Me gusta',
        unlike: 'Quitar me gusta',
        reportTipBtn: 'Reportar este tip',
        editTip: 'Editar tip',
        deleteTip: 'Eliminar tip',
        confirmDelete: '¿Seguro que deseas eliminar este tip?',
        by: 'Por',
        anonymous: 'Anónimo',
        // TipDetailsModal
        tipDetails: 'Detalles del Tip',
        comments: 'Comentarios',
        addComment: 'Escribe un comentario...',
        noComments: 'Aún no hay comentarios. ¡Sé el primero!',
        send: 'Enviar',
        report: 'Reportar',
        close: 'Cerrar',
        loginToComment: 'Inicia sesión para comentar.',
        // AuthModal
        loginTitle: 'Iniciar sesión',
        registerTitle: 'Crear cuenta',
        nameField: 'Tu nombre',
        emailField: 'Correo electrónico',
        passwordField: 'Contraseña',
        namePlaceholderAuth: 'Ej. María García',
        nameRequired: 'El nombre es requerido.',
        passwordLength: 'La contraseña debe tener al menos 6 caracteres.',
        loggingIn: 'Iniciando sesión...',
        registering: 'Creando cuenta...',
        switchToRegister: '¿No tienes cuenta? Regístrate',
        switchToLogin: '¿Ya tienes cuenta? Inicia sesión',
        forgotPasswordBtn: '¿Olvidaste tu contraseña?',
        recoveryTitle: 'Recuperar contraseña',
        recoverySubtitle: 'Te enviaremos un enlace a tu correo',
        recoveryEmailReq: 'Ingresa tu correo',
        recoverySuccess: 'Te hemos enviado un enlace para restablecer tu contraseña. Revisa tu bandeja.',
        recoverySubmitBtn: 'Enviar enlace',
        recoverySending: 'Enviando...',
        backToLogin: 'Volver al inicio de sesión',
        // ReportModal
        reportTip: 'Reportar Tip',
        reportingTip: 'Estás reportando:',
        reportReason: '¿Cuál es el motivo?',
        spamReason: 'Spam o publicidad',
        fakeReason: 'Información falsa o engañosa',
        inappropriateReason: 'Contenido inapropiado',
        otherReason: 'Otro',
        details: 'Detalles adicionales (opcional)',
        detailsPlaceholder: 'Proporciona más información...',
        sendReport: 'Enviar reporte',
        reportSent: '¡Reporte enviado!',
        reportThanks: 'Gracias por ayudar a mantener la comunidad segura. Un moderador revisará este tip.',
        // CreateTipModal
        publishTipTitle: 'Publicar nuevo tip',
        confirmation: 'Confirmación',
        titleLabel: 'Título del tip',
        titlePlaceholder: 'Ej. Reduce tu consumo de agua',
        descriptionLabel: 'Descripción',
        descriptionPlaceholder: 'Describe tu práctica sustentable...',
        categoryLabel: 'Categoría',
        nameLabel: 'Tu nombre (opcional)',
        namePlaceholder: 'Se mostrará "Anónimo" si no escribes nada',
        designLabel: 'Diseño del post-it',
        selected: 'Seleccionado',
        cancel: 'Cancelar',
        publish: 'Publicar',
        addSticker: 'Agregar ticker',
        maxStickers: 'Max 5 tickers',
        removeSticker: 'Quitar',
        next: 'Siguiente',
        guestConfirmTitle: '¿Publicar como visitante?',
        guestConfirmText: 'Puedes publicar este tip como visitante, pero no podrás editarlo ni eliminarlo después. Para administrar tus tips, considera crear una cuenta gratuita.',
        publishAnyway: 'Publicar de todas formas',
        editBack: 'Editar',
        saveChanges: 'Guardar cambios',
        // Profile
        myTips: 'Mis Tips',
        likedTips: 'Tips con like',
        notificationTab: 'Notificaciones',
        noMyTips: 'Aún no has publicado ningún tip.',
        noLikedTips: 'No has dado like a ningún tip todavía.',
        noNotifText: 'Aquí verás tus notificaciones.',
        doubleTapHint: 'Dale doble tap o usa el botón de like en cualquier tip.',
        backToFeed: 'Volver al feed',
        activeTips: 'Tips activos',
        totalLikes: 'Me gustas',
        suspended: 'Suspendidos',
        editProfileTitle: 'Editar Perfil',
        avatarLabel: 'Elige tu avatar',
        avatarPreview: 'Vista previa',
        // ModeratorDashboard
        modDashboardTitle: 'Panel de Moderación',
        modHello: 'Hola',
        modTotalTips: 'Tips totales',
        modReported: 'Reportados',
        modReports: 'Reportes',
        modSuspended: 'Suspendidos',
        modComments: 'Comentarios',
        modTabReported: 'Reportados',
        modTabAll: 'Todos',
        modTabComments: 'Comentarios',
        modNoTipsReported: 'No hay tips reportados actualmente.',
        modNoTipsAll: 'No hay tips actualmente.',
        modNoComments: 'No hay comentarios.',
        modBy: 'Por',
        modReason: 'Motivo:',
        modSentOn: 'Enviado el',
        modRestoreBtn: 'Restaurar',
        modEvidence: 'Evidencia de Reportes',
        modIn: 'En',
        modDeletedTip: 'tip eliminado',
        modPromptDelete: 'Motivo de eliminación (se enviará al autor):',
        modDefaultReason: 'Incumplimiento de las normas de la comunidad',
        moderatorPanel: 'Panel de Moderación',
        pendingReports: 'Reportes pendientes',
        tipsReported: 'tips reportados',
        noReports: 'No hay reportes pendientes.',
        allClear: '¡Todo está en orden!',
        suspend: 'Suspender',
        reinstate: 'Restituir',
        deleteForMod: 'Eliminar',
        viewTip: 'Ver tip',
        tipSuspended: 'Suspendido',
        tipActive: 'Activo',
        reportedBy: 'Reportado por',
        reportReasonLabel: 'Motivo',
        moderateAll: 'Administrar todos los tips',
        /* WelcomeModal
        welcomeTitle: 'Bienvenido a Eco Tips',
        welcomeSubtitle: 'Tu comunidad sustentable',
        welcomeCreate: 'Crea tips con la comunidad',
        welcomeSupport: 'Apoya iniciativas que te gusten',
        welcomeShare: 'Comparte tu conocimiento',
        welcomeQuality: 'Mantén el contenido de calidad',
        welcomeGuest: 'Sin registro, modos de exploración',
        welcomeStart: 'Comenzar a explorar',
        welcomeBody: 'Un espacio para compartir y aprender sobre prácticas sustentables. Juntos hacemos la diferencia.',
        communityNote: 'Comunidad: Sé amable y respetuoso. Todas las ideas son valiosas.',
        */
        welcomeTitle: 'Welcome to Eco Tips',
        welcomeSubtitle: 'Your sustainable community',
        welcomeCreate: 'Create tips with the community',
        welcomeSupport: 'Support initiatives you like',
        welcomeShare: 'Share your knowledge',
        welcomeQuality: 'Keep content quality high',
        welcomeGuest: 'No sign-up needed to explore',
        welcomeStart: 'Start exploring',
        welcomeBody: 'A place to share and learn about sustainable practices. Together we make a difference.',
        communityNote: 'Community: Be kind and respectful. All ideas are valuable.',
        // Footer
        footerDev: 'Desarrollado con',
        footerText: 'para un futuro más verde.',
        footerHome: 'Inicio',
        footerLegal: 'Normas y Privacidad',
        // Legal page
        legalTitle: 'Normas, Estándares y Privacidad',
        reportSuccess: '¡Reporte enviado!',
        reportSuccessText: 'Gracias, nuestro equipo lo revisará pronto.',
        // Profile Settings & Auth
        changePassword: 'Cambiar Contraseña',
        deleteAccount: 'Eliminar Cuenta',
        resendVerification: 'Reenviar correo de verificación',
        unverifiedAlert: 'Por seguridad, confirma tu correo electrónico.',
        viewingAuthor: 'Viendo los tips de:',
        clearFilter: 'Mostrar todos',
        // Custom Alert modal
        deleteAccountTitle: '¿Eliminar Cuenta?',
        deleteAccountMsg: 'Esta acción borrará tus datos y es permanentemente irreversible. ¿Estás absolutamente seguro?',
        deleteYes: 'Sí, eliminar',
        // Modal Forms
        titleLabel: 'Título',
        descLabel: 'Descripción',
        categoryLabel: 'Categoría',
        designLabel: 'Diseño del post-it',
        stickerLabel: 'Stickers',
        stickerHint: 'Selecciona stickers para decorar tu post-it',
        stickerDragHint: 'Arrastra los stickers para acomodarlos. Toca la X para quitarlos.',
        editReason: 'Motivo de edición (se enviará al autor):',
        defaultEditReason: 'Ajuste a las normas de la comunidad',
        catWaste: 'Residuos',
        catRecycling: 'Reciclaje',
        catEnergy: 'Energía',
        catNature: 'Naturaleza',
        authorNameOptional: 'Tu nombre (opcional)',
        selectedDesign: 'Seleccionado:',
        previewLabel: 'Vista Previa',
        previewTitleFallback: 'Título preview',
        previewDescFallback: 'La descripción de tu tip aparecerá aquí...',
        publishTipBtn: 'Publicar Tip',
        saveTipBtn: 'Guardar cambios',
        settings: 'Ajustes',
        changePasswordTitle: 'Cambiar Contraseña',
        changePasswordMsg: 'Te enviaremos un correo oficial seguro para que puedas establecer una nueva contraseña. ¿Proceder?',
        sendEmailBtn: 'Enviar correo',
        emailSentTitle: 'Correo Enviado',
        emailSentMsg: 'Revisa tu bandeja de entrada. Si no lo ves, revisa la carpeta de Spam.',
        understood: 'Entendido',
        cancelBtn: 'Cancelar',
        errorTitle: 'Hubo un error',
        changePasswordNeedsVerification: 'Para cambiar tu contraseña primero debes verificar tu correo electrónico. ¿Quieres que te reenviemos el correo de verificación?',
        verificationSentMsg: 'Te enviamos un correo de verificación. Revisa tu bandeja (y la carpeta de Spam). Si pusiste un correo incorrecto al registrarte, elimina tu cuenta y crea una nueva con el correo correcto.',
        err_invalid_login: 'Correo o contraseña incorrectos o inexistentes.',
        err_email_in_use: 'Este correo ya está registrado.',
        err_register_error: 'Hubo un error al crear la cuenta.',
        err_user_not_found: 'No hay usuario registrado con este correo.',
        err_reset_error: 'Error al enviar correo de recuperación.',
        err_requires_recent_login: 'Por seguridad, debes cerrar sesión y volver a entrar antes de borrar tu cuenta.',
        err_delete_account_error: 'Error al eliminar cuenta. Intenta más tarde.',
        err_no_user: 'No hay usuario.',
        err_too_many_requests: 'Demasiadas solicitudes. Espera un momento.',
        err_send_email_error: 'Error al enviar correo.',

        // Social (ES)
        followers: 'Seguidores',
        following: 'Siguiendo',
        friends: 'Amigos',
        addFriend: 'Añadir Amigo',
        friendRequestSent: 'Solicitud Enviada',
        removeFriend: 'Eliminar Amigo',
        confirmDeleteFriend: '¿Seguro que deseas eliminar a este usuario de tus amigos?',
        follow: 'Seguir',
        unfollow: 'Siguiendo',
        cancelRequest: 'Cancelar',
        friendRequests: 'Solicitudes de Amistad',
        accept: 'Aceptar',
        reject: 'Rechazar',
        searchUsers: 'Buscar Personas',
        searchUsersPlaceholder: 'Busca por nombre o #ID...',
        noUsersFound: 'No se encontraron usuarios.',
        viewProfile: 'Ver Perfil',
        connections: 'Conexiones',
        pending: 'Pendiente',
        searchIdTitle: 'Tu ID Búsqueda:',
        copied: 'Copiado',
        //404
        errorSubtitle: 'Lo sentimos, algo no salió como esperábamos. Te redirigiremos automáticamente al inicio en un momento.',
        errorRedirecting: 'Volviendo en',
        errorSeconds: 'segundos',
        errorBtn: 'Ir al inicio ahora',
    },
    en: {
        appSubtitle: 'Share and discover sustainable tips',
        notifications: 'Notifications',
        noNotifications: 'No notifications',
        markAllRead: 'Mark all as read',
        myProfile: 'My Profile',
        moderation: 'Moderation',
        logout: 'Log out',
        login: 'Log in',
        register: 'Sign up',
        roleModerator: 'Moderator',
        roleUser: 'User',
        publishTip: 'Post Tip',
        mostRecent: 'Most recent',
        mostPopular: 'Most popular',
        oldest: 'Oldest',
        noTipsCategory: 'No tips in this category. Be the first to contribute!',
        loadMore: 'Load more tips',
        endOfList: 'You have reached the end',
        all: 'All',
        waste: 'Waste',
        recycling: 'Recycling',
        energy: 'Energy',
        nature: 'Nature',
        like: 'Like',
        unlike: 'Unlike',
        reportTipBtn: 'Report this tip',
        editTip: 'Edit tip',
        deleteTip: 'Delete tip',
        confirmDelete: 'Are you sure you want to delete this tip?',
        by: 'By',
        anonymous: 'Anonymous',
        tipDetails: 'Tip Details',
        comments: 'Comments',
        addComment: 'Write a comment...',
        noComments: 'No comments yet. Be the first!',
        send: 'Send',
        report: 'Report',
        close: 'Close',
        loginToComment: 'Log in to comment.',
        loginTitle: 'Log in',
        registerTitle: 'Create account',
        nameField: 'Your name',
        emailField: 'Email address',
        passwordField: 'Password',
        namePlaceholderAuth: 'E.g. Maria Garcia',
        nameRequired: 'Name is required.',
        passwordLength: 'Password must be at least 6 characters.',
        loggingIn: 'Logging in...',
        registering: 'Creating account...',
        switchToRegister: "Don't have an account? Sign up",
        switchToLogin: 'Already have an account? Log in',
        forgotPasswordBtn: 'Forgot your password?',
        recoveryTitle: 'Recover password',
        recoverySubtitle: 'We will send a link to your email',
        recoveryEmailReq: 'Enter your email',
        recoverySuccess: 'We have sent you a link to reset your password. Check your inbox.',
        recoverySubmitBtn: 'Send link',
        recoverySending: 'Sending...',
        backToLogin: 'Back to login',
        reportTip: 'Report Tip',
        reportingTip: 'You are reporting:',
        reportReason: 'What is the reason?',
        spamReason: 'Spam or advertising',
        fakeReason: 'False or misleading information',
        inappropriateReason: 'Inappropriate content',
        otherReason: 'Other',
        details: 'Additional details (optional)',
        detailsPlaceholder: 'Provide more information...',
        sendReport: 'Send report',
        reportSent: 'Report sent!',
        reportThanks: 'Thank you for helping keep the community safe. A moderator will review this tip.',
        publishTipTitle: 'Post new tip',
        confirmation: 'Confirmation',
        titleLabel: 'Tip title',
        titlePlaceholder: 'E.g. Reduce your water consumption',
        descriptionLabel: 'Description',
        descriptionPlaceholder: 'Describe your sustainable practice...',
        categoryLabel: 'Category',
        nameLabel: 'Your name (optional)',
        namePlaceholder: '"Anonymous" will show if you leave this blank',
        designLabel: 'Post-it design',
        selected: 'Selected',
        cancel: 'Cancel',
        publish: 'Publish',
        addSticker: 'Add ticker',
        maxStickers: 'Max 5 tickers',
        removeSticker: 'Remove',
        next: 'Next',
        guestConfirmTitle: 'Publish as guest?',
        guestConfirmText: "You can publish this tip as a guest, but you won't be able to edit or delete it afterwards. Consider creating a free account to manage your tips.",
        publishAnyway: 'Publish anyway',
        editBack: 'Edit',
        saveChanges: 'Save changes',
        editTipMod: 'Edit tip (Moderator)',
        // Profile
        myTips: 'My Tips',
        likedTips: 'Liked Tips',
        notificationTab: 'Notifications',
        noMyTips: "You haven't published any tips yet.",
        noLikedTips: "You haven't liked any tips yet.",
        noNotifText: 'Your notifications will appear here.',
        doubleTapHint: 'Double-tap or use the like button on any tip.',
        backToFeed: 'Back to feed',
        activeTips: 'Active tips',
        totalLikes: 'Likes',
        suspended: 'Suspended',
        editProfileTitle: 'Edit Profile',
        avatarLabel: 'Choose your avatar',
        avatarPreview: 'Preview',
        // Profile Settings & Auth
        changePassword: 'Change Password',
        deleteAccount: 'Delete Account',
        resendVerification: 'Resend verification email',
        unverifiedAlert: 'For security reasons, please confirm your email address.',
        viewingAuthor: 'Viewing tips by:',
        clearFilter: 'Show all',
        // Custom Alert modal
        deleteAccountTitle: 'Delete Account?',
        deleteAccountMsg: 'This action will erase your data and is permanently irreversible. Are you absolutely sure?',
        deleteYes: 'Yes, delete',
        // Modal Forms
        titleLabel: 'Title',
        descLabel: 'Description',
        categoryLabel: 'Category',
        designLabel: 'Post-it Design',
        stickerLabel: 'Stickers',
        stickerHint: 'Select stickers to decorate your post-it',
        stickerDragHint: 'Drag to arrange your stickers. Tap the X to remove them.',
        editReason: 'Reason for editing (will be sent to the author):',
        defaultEditReason: 'Adjustment to community guidelines',
        catWaste: 'Waste',
        catRecycling: 'Recycling',
        catEnergy: 'Energy',
        catNature: 'Nature',
        authorNameOptional: 'Your name (optional)',
        selectedDesign: 'Selected:',
        previewLabel: 'Live Preview',
        previewTitleFallback: 'Preview Title',
        previewDescFallback: 'The description of your tip will appear here...',
        publishTipBtn: 'Publish Tip',
        saveTipBtn: 'Save changes',
        settings: 'Settings',
        changePasswordTitle: 'Change Password',
        changePasswordMsg: 'We will send you an official secure email so you can set a new password. Proceed?',
        sendEmailBtn: 'Send email',
        emailSentTitle: 'Email Sent',
        emailSentMsg: 'Check your inbox. If you don\'t see it, check your Spam folder.',
        understood: 'Understood',
        cancelBtn: 'Cancel',
        errorTitle: 'There was an error',
        changePasswordNeedsVerification: 'To change your password you must first verify your email address. Would you like us to resend the verification email?',
        verificationSentMsg: 'We sent you a verification email. Check your inbox (and Spam folder). If you registered with the wrong email address, please delete your account and create a new one with the correct email.',
        err_invalid_login: 'Invalid email or password.',
        err_email_in_use: 'This email is already registered.',
        err_register_error: 'There was an error creating the account.',
        err_user_not_found: 'No user registered with this email.',
        err_reset_error: 'Error sending recovery email.',
        err_requires_recent_login: 'For security, you must log out and log back in before deleting your account.',
        err_delete_account_error: 'Error deleting account. Try again later.',
        err_no_user: 'No user found.',
        err_too_many_requests: 'Too many requests. Please wait a moment.',
        err_send_email_error: 'Error sending email.',
        modDashboardTitle: 'Moderation Panel',
        modHello: 'Hello',
        modTotalTips: 'Total Tips',
        modReported: 'Reported',
        modReports: 'Reports',
        modSuspended: 'Suspended',
        modComments: 'Comments',
        modTabReported: 'Reported',
        modTabAll: 'All',
        modTabComments: 'Comments',
        modNoTipsReported: 'No reported tips currently.',
        modNoTipsAll: 'No tips currently.',
        modNoComments: 'No comments.',
        modBy: 'By',
        modReason: 'Reason:',
        modSentOn: 'Sent on',
        modRestoreBtn: 'Restore',
        modEvidence: 'Report Evidence',
        modIn: 'In',
        modDeletedTip: 'deleted tip',
        modPromptDelete: 'Reason for deletion (will be sent to author):',
        modDefaultReason: 'Violation of community guidelines',
        moderatorPanel: 'Moderation Panel',
        pendingReports: 'Pending reports',
        tipsReported: 'reported tips',
        noReports: 'No pending reports.',
        allClear: 'All clear!',
        suspend: 'Suspend',
        reinstate: 'Reinstate',
        deleteForMod: 'Delete',
        viewTip: 'View tip',
        tipSuspended: 'Suspended',
        tipActive: 'Active',
        reportedBy: 'Reported by',
        reportReasonLabel: 'Reason',
        moderateAll: 'Manage all tips',
        welcomeTitle: 'Welcome to Eco Tips',
        welcomeSubtitle: 'Your sustainable community',
        welcomeCreate: 'Create tips with the community',
        welcomeSupport: 'Support initiatives you like',
        welcomeShare: 'Share your knowledge',
        welcomeQuality: 'Keep content quality high',
        welcomeGuest: 'No sign-up needed to explore',
        welcomeStart: 'Start exploring',
        welcomeBody: 'A place to share and learn about sustainable practices. Together we make a difference.',
        communityNote: 'Community: Be kind and respectful. All ideas are valuable.',
        // Footer
        footerDev: 'Made with',
        footerText: 'for a greener future.',
        footerHome: 'Home',
        footerLegal: 'Standards & Privacy',
        legalTitle: 'Standards, Norms & Privacy',
        reportSuccess: 'Report sent!',
        reportSuccessText: 'Thanks, our team will review it soon.',

        // (EN)
        followers: 'Followers',
        following: 'Following',
        friends: 'Friends',
        addFriend: 'Add Friend',
        friendRequestSent: 'Request Sent',
        removeFriend: 'Remove Friend',
        confirmDeleteFriend: 'Are you sure you want to remove this user from your friends?',
        follow: 'Follow',
        unfollow: 'Following',
        cancelRequest: 'Cancel Request',
        friendRequests: 'Friend Requests',
        accept: 'Accept',
        reject: 'Reject',
        searchUsers: 'Search People',
        searchUsersPlaceholder: 'Search by name or #ID...',
        noUsersFound: 'No users found.',
        viewProfile: 'View Profile',
        connections: 'Connections',
        pending: 'Pending',
        searchIdTitle: 'Your Search ID:',
        copied: 'Copied',
        // 404
        errorSubtitle: 'Sorry, something didn\'t go as expected. You will be redirected to the home page shortly.',
        errorRedirecting: 'Redirecting in',
        errorSeconds: 'seconds',
        errorBtn: 'Go to home now',
    },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
    const [lang, setLang] = useState(() => localStorage.getItem('ecotips_lang') || 'es');

    const toggleLang = useCallback(() => {
        setLang(prev => {
            const next = prev === 'es' ? 'en' : 'es';
            localStorage.setItem('ecotips_lang', next);
            return next;
        });
    }, []);

    const t = useCallback((key) => translations[lang][key] || translations['es'][key] || key, [lang]);

    const value = useMemo(() => ({ lang, toggleLang, t }), [lang, toggleLang, t]);

    return (
        <LanguageContext.Provider value={value}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    return useContext(LanguageContext);
}
